server: ${SERVER}
heartbeat: 10.0
workdir: ./storage

datasources:
  - name: california1
    type: csv
    path: "/ferdelance/data/california_housing.MedInc1.csv"
    kind: file
    token: 58981bcbab77ef4b8e01207134c38873e0936a9ab88cd76b243a2e2c85390b94
